import {
  Scale,
  Car,
  Building2,
  Users,
  HeartHandshake,
  Briefcase,
  Landmark,
  FileText,
  ShieldCheck,
  Gavel,
  Network,
  Sparkles,
} from "lucide-react";

export type Law = {
  id: string;
  name: string;
  articles: number;
  updated: string;
  icon: React.ComponentType<{ className?: string }>;
  color: string;
  category?: string;
  source?: string;
};

export const laws: Law[] = [
  { id: "civil", name: "القانون المدني", articles: 2478, updated: "2025-11", icon: Scale, color: "#1E3A8A", category: "civil", source: "الوقائع العراقية" },
  { id: "penal", name: "قانون العقوبات", articles: 462, updated: "2025-09", icon: Gavel, color: "#0F172A", category: "penal", source: "الوقائع العراقية" },
  { id: "personal", name: "قانون الأحوال الشخصية", articles: 160, updated: "2025-12", icon: HeartHandshake, color: "#F59E0B", category: "personal", source: "الوقائع العراقية" },
  { id: "labor", name: "قانون العمل", articles: 145, updated: "2025-10", icon: Users, color: "#10B981", category: "labor", source: "الوقائع العراقية" },
  { id: "traffic", name: "قانون المرور", articles: 98, updated: "2025-08", icon: Car, color: "#3B82F6", category: "traffic", source: "الوقائع العراقية" },
  { id: "companies", name: "قانون الشركات", articles: 312, updated: "2025-11", icon: Building2, color: "#1E3A8A", category: "companies", source: "الوقائع العراقية" },
  { id: "investment", name: "قانون الاستثمار", articles: 74, updated: "2025-07", icon: Landmark, color: "#F59E0B", category: "investment", source: "الوقائع العراقية" },
  { id: "commercial", name: "القانون التجاري", articles: 540, updated: "2025-06", icon: Briefcase, color: "#3B82F6", category: "commercial", source: "الوقائع العراقية" },
];

export type Lawyer = {
  id: string;
  name: string;
  slug?: string; // English slug for URL (e.g., "sara-nasser")
  city: string;
  specialization: string;
  experience: number;
  rating: number;
  reviews: number;
  verified: boolean;
  price: number;
  online: boolean;
  gender: "male" | "female";
  languages: string[];
  bio: string;
  initials: string;
  hue: string;
  whatsapp?: string;
  telegram?: string;
  facebook?: string;
  instagram?: string;
  // Auth / login credentials
  email?: string;
  password?: string;
  photoUrl?: string;
  // DB reference
  userId?: string;
  // Points & rewards
  points?: number;
  // Promotion system
  promoted?: boolean; // Currently promoted/featured
  promotionStatus?: "none" | "pending" | "approved" | "rejected"; // Promotion request status
  promotionPlan?: {
    city: string; // Which city to appear in
    type: "monthly" | "yearly"; // Plan type
    startDate?: string; // When promotion started
    expiryDate?: string; // When promotion expires
  };
};

export function lawyerSlug(lawyer: Lawyer): string {
  // If lawyer has a custom English slug, use it
  if (lawyer.slug && lawyer.slug.trim()) {
    return lawyer.slug.trim().toLowerCase().replace(/\s+/g, '-');
  }
  // Otherwise, generate from Arabic name
  const clean = lawyer.name
    .replace(/^(أ\.د\.|الأستاذ|المحامية|أ\.|د\.)\s*/i, '')
    .replace(/\s+/g, '-')
    .toLowerCase();
  return clean;
}

export const lawyers: Lawyer[] = [
  {
    id: "l1",
    name: "أ.د. محمد عبد الكريم",
    slug: "mohammed-abdelkarim",
    city: "بغداد",
    specialization: "القانون المدني",
    experience: 22,
    rating: 4.9,
    reviews: 318,
    verified: true,
    price: 50,
    online: true,
    gender: "male",
    languages: ["العربية", "الإنجليزية"],
    bio: "خبير في المنازعات العقارية والعقود التجارية مع خبرة واسعة أمام محاكم الاستئناف.",
    initials: "مع",
    hue: "from-blue-600 to-indigo-700",
    whatsapp: "+9647701112233",
    telegram: "@lawyer_mohammed",
    facebook: "mohammed.abdelkarim.law",
    instagram: "lawyer.mohammed.legal",
  },
  {
    id: "l2",
    name: "المحامية سارة ناصر",
    slug: "sara-nasser",
    city: "أربيل",
    specialization: "الأحوال الشخصية",
    experience: 14,
    rating: 4.8,
    reviews: 204,
    verified: true,
    price: 40,
    online: true,
    gender: "female",
    languages: ["العربية", "الكردية", "الإنجليزية"],
    bio: "متخصصة في قضايا الأحوال الشخصية والحضانة والنفقة بأسلوب إنساني واحترافي.",
    initials: "سن",
    hue: "from-amber-500 to-orange-600",
    whatsapp: "+9647502223344",
    telegram: "@lawyer_sara",
    facebook: "sara.nasser.law",
    instagram: "lawyer.sara.legal",
  },
  {
    id: "l3",
    name: "الأستاذ خالد العبيدي",
    slug: "khaled-alubaidi",
    city: "البصرة",
    specialization: "القانون الجنائي",
    experience: 18,
    rating: 4.7,
    reviews: 176,
    verified: true,
    price: 60,
    online: false,
    gender: "male",
    languages: ["العربية"],
    bio: "محامٍ جنائي يمثل المتهمين في القضايا الجسيمة ويتميز بالمرافعات الخطابية.",
    initials: "خع",
    hue: "from-slate-700 to-slate-900",
    whatsapp: "+9647703334455",
    telegram: "@lawyer_khaled",
    facebook: "khaled.alubaidi.law",
  },
  {
    id: "l4",
    name: "المحامية رنا جاسم",
    slug: "rana-jasim",
    city: "بغداد",
    specialization: "قانون العمل",
    experience: 9,
    rating: 4.9,
    reviews: 142,
    verified: true,
    price: 35,
    online: true,
    gender: "female",
    languages: ["العربية", "الإنجليزية"],
    bio: "تدافع عن حقوق العمال وتتخصص في منازعات الفصل التعسفي ومكافآت نهاية الخدمة.",
    initials: "رج",
    hue: "from-emerald-500 to-teal-600",
    whatsapp: "+9647804445566",
    telegram: "@lawyer_rana",
    facebook: "rana.jasim.law",
    instagram: "lawyer.rana.legal",
  },
  {
    id: "l5",
    name: "الأستاذ عمر فؤاد",
    slug: "omar-fouad",
    city: "النجف",
    specialization: "القانون التجاري",
    experience: 16,
    rating: 4.6,
    reviews: 98,
    verified: false,
    price: 45,
    online: true,
    gender: "male",
    languages: ["العربية", "الإنجليزية"],
    bio: "مستشار قانوني للشركات الناشئة وعقود الاستثمار والتأسيس التجاري.",
    initials: "عف",
    hue: "from-blue-500 to-cyan-600",
    whatsapp: "+9647816667788",
    telegram: "@lawyer_omar",
  },
  {
    id: "l6",
    name: "المحامية هدى كريم",
    slug: "huda-kareem",
    city: "كربلاء",
    specialization: "العقارات",
    experience: 11,
    rating: 4.8,
    reviews: 121,
    verified: true,
    price: 38,
    online: false,
    gender: "female",
    languages: ["العربية"],
    bio: "خبرة في تسجيل العقار وتقسيم التركات والمنازعات العقارية الوقفية.",
    initials: "هك",
    hue: "from-purple-500 to-fuchsia-600",
    whatsapp: "+9647704445566",
    telegram: "@lawyer_huda",
    facebook: "huda.kareem.law",
    instagram: "lawyer.huda.legal",
  },
  {
    id: "l7",
    name: "الأستاذ ياسر العاني",
    slug: "yasser-alani",
    city: "بغداد",
    specialization: "القانون الإداري",
    experience: 20,
    rating: 4.7,
    reviews: 187,
    verified: true,
    price: 55,
    online: true,
    gender: "male",
    languages: ["العربية", "الإنجليزية", "الفرنسية"],
    bio: "يمثل الموظفين في الطعون الإدارية أمام محكمة القضاء الإداري.",
    initials: "يع",
    hue: "from-indigo-600 to-blue-700",
    whatsapp: "+9647827778899",
    telegram: "@lawyer_yasser",
    facebook: "yasser.alani.law",
    instagram: "lawyer.yasser.legal",
  },
  {
    id: "l8",
    name: "المحامية ليلى حسن",
    slug: "layla-hassan",
    city: "أربيل",
    specialization: "الأحوال الشخصية",
    experience: 7,
    rating: 4.9,
    reviews: 89,
    verified: false,
    price: 30,
    online: true,
    gender: "female",
    languages: ["العربية", "الكردية"],
    bio: "تركز على التسويات الودية في قضايا الطلاق والميراث بخصوصية تامة.",
    initials: "لح",
    hue: "from-rose-500 to-pink-600",
    whatsapp: "+9647515556677",
    telegram: "@lawyer_layla",
    instagram: "lawyer.layla.legal",
  },
  {
    id: "l9",
    name: "أ. أحمد خليل",
    slug: "ahmed-khalil",
    city: "بغداد",
    specialization: "قانون الشركات",
    experience: 12,
    rating: 4.7,
    reviews: 156,
    verified: true,
    price: 50,
    online: true,
    gender: "male",
    languages: ["العربية", "الإنجليزية"],
    bio: "مستشار قانوني متخصص في تأسيس الشركات والصفقات التجارية الكبرى والامتثال التنظيمي.",
    initials: "أخ",
    hue: "from-blue-600 to-indigo-700",
    promoted: true,
    whatsapp: "+9647705556677",
    telegram: "@lawyer_ahmed",
  },
  {
    id: "l10",
    name: "المحامية فاطمة حسين",
    slug: "fatima-hussein",
    city: "النجف",
    specialization: "القانون الدستوري",
    experience: 15,
    rating: 4.8,
    reviews: 134,
    verified: true,
    price: 55,
    online: false,
    gender: "female",
    languages: ["العربية"],
    bio: "متخصصة في القانون الدستوري والمنازعات الإدارية أمام مجلس الدولة.",
    initials: "فح",
    hue: "from-purple-500 to-fuchsia-600",
    promoted: true,
    whatsapp: "+9647828889900",
    telegram: "@lawyer_fatima",
  },
  {
    id: "l11",
    name: "الأستاذ علي جعفر",
    slug: "ali-jafar",
    city: "البصرة",
    specialization: "القانون المالي",
    experience: 20,
    rating: 4.6,
    reviews: 198,
    verified: true,
    price: 65,
    online: true,
    gender: "male",
    languages: ["العربية", "الإنجليزية"],
    bio: "خبير في القانون المالي والضرائب والمعاملات المالية أمام الجهات الحكومية.",
    initials: "عج",
    hue: "from-slate-700 to-slate-900",
    whatsapp: "+9647709990011",
    telegram: "@lawyer_ali",
  },
  {
    id: "l12",
    name: "المحامية نور سالم",
    slug: "noor-salem",
    city: "الموصل",
    specialization: "القانون الصحي",
    experience: 8,
    rating: 4.9,
    reviews: 87,
    verified: false,
    price: 35,
    online: true,
    gender: "female",
    languages: ["العربية", "الإنجليزية"],
    bio: "متخصصة في المسؤولية الطبية والقانون الصحي وحقوق المرضى.",
    initials: "نس",
    hue: "from-emerald-500 to-teal-600",
    whatsapp: "+9647511112233",
    telegram: "@lawyer_noor",
  },
  {
    id: "l13",
    name: "الأستاذ حسام مهدي",
    slug: "hsam-mahdi",
    city: "كركوك",
    specialization: "قانون الملكية الفكرية",
    experience: 10,
    rating: 4.5,
    reviews: 76,
    verified: true,
    price: 45,
    online: true,
    gender: "male",
    languages: ["العربية", "الكردية", "الإنجليزية"],
    bio: "مستشار في حماية العلامات التجارية وبراءات الاختراع والحقوق الفكرية.",
    initials: "حم",
    hue: "from-blue-500 to-cyan-600",
    whatsapp: "+9647702223344",
    telegram: "@lawyer_hsam",
  },
  {
    id: "l14",
    name: "المحامية دعاء كريم",
    slug: "doaa-kareem",
    city: "السليمانية",
    specialization: "الأحوال الشخصية",
    experience: 6,
    rating: 4.8,
    reviews: 65,
    verified: false,
    price: 30,
    online: true,
    gender: "female",
    languages: ["العربية", "الكردية"],
    bio: "متخصصة في قضايا الأسرة والحضانة والنفقة بأسلوب حنون واحترافي.",
    initials: "دك",
    hue: "from-rose-500 to-pink-600",
    whatsapp: "+9647503334455",
    telegram: "@lawyer_doaa",
  },
  {
    id: "l15",
    name: "الأستاذ كرار ناصر",
    slug: "karar-nasser",
    city: "بغداد",
    specialization: "القانون الجنائي",
    experience: 25,
    rating: 4.9,
    reviews: 289,
    verified: true,
    price: 70,
    online: false,
    gender: "male",
    languages: ["العربية"],
    bio: "محامٍ جنائي بارز يمثّل في القضايا الكبرى أمام محكمة الجنايات المركزية.",
    initials: "كن",
    hue: "from-indigo-600 to-blue-700",
    promoted: true,
    whatsapp: "+9647814445566",
    telegram: "@lawyer_karar",
  },
  {
    id: "l16",
    name: "المحامية مريم عادل",
    slug: "mariam-adel",
    city: "الناصرية",
    specialization: "القانون البيئي",
    experience: 7,
    rating: 4.6,
    reviews: 52,
    verified: false,
    price: 35,
    online: true,
    gender: "female",
    languages: ["العربية", "الإنجليزية"],
    bio: "متخصصة في القضايا البيئية والتلوث وحماية الموارد الطبيعية.",
    initials: "مع",
    hue: "from-teal-500 to-emerald-600",
    whatsapp: "+9647706667788",
    telegram: "@lawyer_mariam",
  },
  {
    id: "l17",
    name: "الأستاذ صادق حيدر",
    slug: "sadiq-haider",
    city: "الحلة",
    specialization: "القانون الدولي",
    experience: 18,
    rating: 4.7,
    reviews: 143,
    verified: true,
    price: 60,
    online: true,
    gender: "male",
    languages: ["العربية", "الإنجليزية", "الفرنسية"],
    bio: "خبير في القانون الدولي الإنساني والمعاملات الدولية والتحكيم التجاري.",
    initials: "صح",
    hue: "from-red-500 to-rose-600",
    whatsapp: "+9647829990011",
    telegram: "@lawyer_sadiq",
  },
  {
    id: "l18",
    name: "المحامية أمل فوزي",
    slug: "amal-fawzi",
    city: "الكوت",
    specialization: "قانون الهجرة",
    experience: 9,
    rating: 4.8,
    reviews: 98,
    verified: true,
    price: 40,
    online: true,
    gender: "female",
    languages: ["العربية", "الإنجليزية"],
    bio: "متخصصة في قانون الهجرة وتأشيرات العمل والإقامة الدائمة في الدول الأجنبية.",
    initials: "أف",
    hue: "from-amber-500 to-orange-600",
    whatsapp: "+9647708889900",
    telegram: "@lawyer_amal",
  },
  {
    id: "l19",
    name: "الأستاذ باسل رياض",
    slug: "basel-riyadh",
    city: "دهوك",
    specialization: "القانون التجاري",
    experience: 14,
    rating: 4.6,
    reviews: 112,
    verified: true,
    price: 50,
    online: true,
    gender: "male",
    languages: ["العربية", "الكردية", "الإنجليزية"],
    bio: "مستشار قانوني للشركات متعدد الجنسيات والصفقات التجارية العابرة للحدود.",
    initials: "بر",
    hue: "from-slate-700 to-slate-900",
    whatsapp: "+9647512223344",
    telegram: "@lawyer_basel",
  },
  {
    id: "l20",
    name: "المحامية هند عثمان",
    slug: "hind-osman",
    city: "الرمادي",
    specialization: "قانون العمل",
    experience: 11,
    rating: 4.7,
    reviews: 89,
    verified: true,
    price: 40,
    online: false,
    gender: "female",
    languages: ["العربية"],
    bio: "تدافع عن حقوق العمال في قضايا الفصل التعسفي وحوادث العمل والتأمينات.",
    initials: "هع",
    hue: "from-purple-500 to-fuchsia-600",
    whatsapp: "+9647813334455",
    telegram: "@lawyer_hind",
  },
  {
    id: "l21",
    name: "الأستاذ فيصل نوري",
    slug: "faisal-nouri",
    city: "بغداد",
    specialization: "القانون الإداري",
    experience: 22,
    rating: 4.8,
    reviews: 234,
    verified: true,
    price: 60,
    online: true,
    gender: "male",
    languages: ["العربية", "الإنجليزية"],
    bio: "خبير في القضاء الإداري وطعون الموظفين والمنازعات الإدارية أمام محكمة القضاء الإداري.",
    initials: "فن",
    hue: "from-emerald-500 to-teal-600",
    whatsapp: "+9647701112244",
    telegram: "@lawyer_faisal",
  },
  {
    id: "l22",
    name: "المحامية ريم عباس",
    slug: "reem-abbas",
    city: "أربيل",
    specialization: "الملكية الفكرية",
    experience: 5,
    rating: 4.9,
    reviews: 43,
    verified: false,
    price: 35,
    online: true,
    gender: "female",
    languages: ["العربية", "الكردية", "الإنجليزية"],
    bio: "متخصصة في تسجيل العلامات التجارية وحماية حقوق الملكية الفكرية للشركات الناشئة.",
    initials: "رع",
    hue: "from-blue-600 to-indigo-700",
    whatsapp: "+9647504445566",
    telegram: "@lawyer_reem",
  },
  {
    id: "l23",
    name: "الأستاذ جمال قاسم",
    slug: "jamal-qasim",
    city: "النجف",
    specialization: "القانون المدني",
    experience: 19,
    rating: 4.6,
    reviews: 167,
    verified: true,
    price: 50,
    online: false,
    gender: "male",
    languages: ["العربية"],
    bio: "محامٍ مدني متخصص في المنازعات العقارية والعقود والمسؤولية التعاقدية.",
    initials: "جق",
    hue: "from-indigo-600 to-blue-700",
    whatsapp: "+9647825556677",
    telegram: "@lawyer_jamal",
  },
  {
    id: "l24",
    name: "المحامية سماح توفيق",
    slug: "samah-tawfiq",
    city: "كربلاء",
    specialization: "الأحوال الشخصية",
    experience: 13,
    rating: 4.8,
    reviews: 145,
    verified: true,
    price: 45,
    online: true,
    gender: "female",
    languages: ["العربية"],
    bio: "متخصصة في قضايا الزواج والطلاق والحضانة والنفقة بخبرة واسعة أمام المحاكم الشرعية.",
    initials: "ست",
    hue: "from-amber-500 to-orange-600",
    whatsapp: "+9647707778899",
    telegram: "@lawyer_samah",
  },
  {
    id: "l25",
    name: "الأستاذ ماجد جلال",
    slug: "majid-jalal",
    city: "الموصل",
    specialization: "القانون العقاري",
    experience: 16,
    rating: 4.7,
    reviews: 123,
    verified: true,
    price: 55,
    online: true,
    gender: "male",
    languages: ["العربية", "الإنجليزية"],
    bio: "خبير في قانون التسجيل العقاري والمنازعات الوقفية والملكية المشتركة.",
    initials: "مج",
    hue: "from-blue-500 to-cyan-600",
    whatsapp: "+9647518889900",
    telegram: "@lawyer_majid",
  },
  {
    id: "l26",
    name: "المحامية ياسمين علي",
    slug: "yasmin-ali",
    city: "بغداد",
    specialization: "القانون الصحي",
    experience: 10,
    rating: 4.9,
    reviews: 108,
    verified: true,
    price: 45,
    online: true,
    gender: "female",
    languages: ["العربية", "الإنجليزية"],
    bio: "متخصصة في المسؤولية الطبية وNTJ قضايا المستشفيات والتأمين الصحي.",
    initials: "يع",
    hue: "from-rose-500 to-pink-600",
    whatsapp: "+9647812223344",
    telegram: "@lawyer_yasmin",
  },
  {
    id: "l27",
    name: "الأستاذ حسين مجيد",
    slug: "hussein-majid",
    city: "البصرة",
    specialization: "القانون الجنائي",
    experience: 28,
    rating: 4.8,
    reviews: 312,
    verified: true,
    price: 75,
    online: false,
    gender: "male",
    languages: ["العربية"],
    bio: "من أقدم المحامين الجنائيين في البصرة، يمثّل في قضايا جنايات المخدرات والجرائم المالية.",
    initials: "حم",
    hue: "from-slate-700 to-slate-900",
    whatsapp: "+9647704445566",
    telegram: "@lawyer_hussein",
  },
  {
    id: "l28",
    name: "المحامية رشا إبراهيم",
    slug: "rasha-ibrahim",
    city: "كركوك",
    specialization: "الأحوال الشخصية",
    experience: 8,
    rating: 4.7,
    reviews: 74,
    verified: false,
    price: 35,
    online: true,
    gender: "female",
    languages: ["العربية", "الكردية"],
    bio: "متخصصة في الأحوال الشخصية وقضايا الميراث والurf النسائي أمام المحاكم.",
    initials: "ري",
    hue: "from-emerald-500 to-teal-600",
    whatsapp: "+9647826667788",
    telegram: "@lawyer_rasha",
  },
  {
    id: "l29",
    name: "الأستاذ نور الدين سعيد",
    slug: "nour-aldeen-saeed",
    city: "السليمانية",
    specialization: "القانون الدولي",
    experience: 21,
    rating: 4.6,
    reviews: 156,
    verified: true,
    price: 65,
    online: true,
    gender: "male",
    languages: ["العربية", "الكردية", "الإنجليزية"],
    bio: "خبير في القانون الدولي العام والمعاملات الدبلوماسية والتحكيم الدولي.",
    initials: "نس",
    hue: "from-red-500 to-rose-600",
    whatsapp: "+9647519990011",
    telegram: "@lawyer_nour",
  },
  {
    id: "l30",
    name: "المحامية آلاء منصور",
    slug: "alaa-mansour",
    city: "الناصرية",
    specialization: "القانون الإداري",
    experience: 12,
    rating: 4.7,
    reviews: 98,
    verified: true,
    price: 45,
    online: true,
    gender: "female",
    languages: ["العربية"],
    bio: "متخصصة في الطعون الإدارية ومنازعات التوظيف العام أمام محكمة القضاء الإداري.",
    initials: "أم",
    hue: "from-purple-500 to-fuchsia-600",
    whatsapp: "+9647703334455",
    telegram: "@lawyer_alaa",
  },
  {
    id: "l31",
    name: "الأستاذ ثامر حسين",
    slug: "thamer-hussein",
    city: "بغداد",
    specialization: "قانون الهجرة",
    experience: 15,
    rating: 4.8,
    reviews: 178,
    verified: true,
    price: 55,
    online: true,
    gender: "male",
    languages: ["العربية", "الإنجليزية"],
    bio: "مستشار هجرة أول يتعامل مع تأشيرات العمل والإقامة الدائمة واللجوء.",
    initials: "ثح",
    hue: "from-blue-600 to-indigo-700",
    whatsapp: "+9647817778899",
    telegram: "@lawyer_thamer",
  },
  {
    id: "l32",
    name: "المحامية شيماء أحمد",
    slug: "shimaa-ahmed",
    city: "الحلة",
    specialization: "قانون العمل",
    experience: 6,
    rating: 4.5,
    reviews: 48,
    verified: false,
    price: 30,
    online: true,
    gender: "female",
    languages: ["العربية"],
    bio: "متحمسة لحماية حقوق العمال وNTJ منازعات التوظيف والفصل التعسفي.",
    initials: "شأ",
    hue: "from-teal-500 to-emerald-600",
    whatsapp: "+9647702221133",
    telegram: "@lawyer_shimaa",
  },
  {
    id: "l33",
    name: "الأستاذ وليد شاكر",
    slug: "walid-shaker",
    city: "الكوت",
    specialization: "القانون التجاري",
    experience: 17,
    rating: 4.7,
    reviews: 134,
    verified: true,
    price: 50,
    online: false,
    gender: "male",
    languages: ["العربية", "الإنجليزية"],
    bio: "مستشار تجاري خبير في عقود التوزيع والوكالة التجارية والشركة ذات المسؤولية المحدودة.",
    initials: "وش",
    hue: "from-amber-500 to-orange-600",
    whatsapp: "+9647821112233",
    telegram: "@lawyer_walid",
  },
  {
    id: "l34",
    name: "المحامية نجلاء طارق",
    slug: "najla-tariq",
    city: "دهوك",
    specialization: "القانون الدستوري",
    experience: 9,
    rating: 4.8,
    reviews: 67,
    verified: true,
    price: 40,
    online: true,
    gender: "female",
    languages: ["العربية", "الكردية", "الإنجليزية"],
    bio: "متخصصة في القانون الدستوري وحقوق الإنسان والحريات العامة.",
    initials: "нт",
    hue: "from-indigo-600 to-blue-700",
    whatsapp: "+9647514445566",
    telegram: "@lawyer_najla",
  },
  {
    id: "l35",
    name: "الأستاذ كاظم أبو العبد",
    slug: "kazim-abo-alabd",
    city: "الرمادي",
    specialization: "القانون العقاري",
    experience: 24,
    rating: 4.9,
    reviews: 201,
    verified: true,
    price: 60,
    online: false,
    gender: "male",
    languages: ["العربية"],
    bio: "خبير عقاري بخبرة واسعة في تسجيل الأراضي الحكومية وNTJ منازعات الأملاك.",
    initials: "КА",
    hue: "from-slate-700 to-slate-900",
    whatsapp: "+9647705554433",
    telegram: "@lawyer_kazim",
  },
  {
    id: "l36",
    name: "المحامية لمياء خالد",
    slug: "lamia-khaled",
    city: "بغداد",
    specialization: "قانون الملكية الفكرية",
    experience: 7,
    rating: 4.6,
    reviews: 56,
    verified: false,
    price: 40,
    online: true,
    gender: "female",
    languages: ["العربية", "الإنجليزية"],
    bio: "متخصصة في حماية البرمجيات والعلامات التجارية وحقوق المؤلف للشركات التقنية.",
    initials: "لخ",
    hue: "from-emerald-500 to-teal-600",
    whatsapp: "+9647818889900",
    telegram: "@lawyer_lamia",
  },
  {
    id: "l37",
    name: "الأستاذ مصطفى كاظم",
    slug: "mustafa-kazim",
    city: "النجف",
    specialization: "القانون المالي",
    experience: 18,
    rating: 4.7,
    reviews: 145,
    verified: true,
    price: 55,
    online: true,
    gender: "male",
    languages: ["العربية", "الإنجليزية"],
    bio: "خبير مالي متخصص في الضرائب والgyaصلات المالية والقانون المصرفي.",
    initials: "مك",
    hue: "from-blue-500 to-cyan-600",
    whatsapp: "+9647709998877",
    telegram: "@lawyer_mustafa",
  },
  {
    id: "l38",
    name: "المحامية هبة الله عبدالله",
    slug: "heba-allah-abdullah",
    city: "كربلاء",
    specialization: "القانون البيئي",
    experience: 5,
    rating: 4.9,
    reviews: 38,
    verified: false,
    price: 30,
    online: true,
    gender: "female",
    languages: ["العربية"],
    bio: "ناشطة في القانون البيئي وحماية النهر الأزرق من التلوث والمشاريع الضارة.",
    initials: "هع",
    hue: "from-rose-500 to-pink-600",
    whatsapp: "+9647517778899",
    telegram: "@lawyer_heba",
  },
  {
    id: "l39",
    name: "الأستاذ فراس الدوري",
    slug: "feras-aldoori",
    city: "الموصل",
    specialization: "القانون الإداري",
    experience: 14,
    rating: 4.6,
    reviews: 112,
    verified: true,
    price: 50,
    online: true,
    gender: "male",
    languages: ["العربية", "الإنجليزية"],
    bio: "محامٍ إداري يمثل المؤسسات الحكومية في المنازعات الإدارية والعقود الحكومية.",
    initials: "فد",
    hue: "from-red-500 to-rose-600",
    whatsapp: "+9647824445566",
    telegram: "@lawyer_feras",
  },
  {
    id: "l40",
    name: "المحامية سناء محمود",
    slug: "sanaa-mahmoud",
    city: "أربيل",
    specialization: "القانون الدولي",
    experience: 11,
    rating: 4.8,
    reviews: 89,
    verified: true,
    price: 50,
    online: true,
    gender: "female",
    languages: ["العربية", "الكردية", "الإنجليزية", "الفرنسية"],
    bio: "متخصصة في القانون الدولي الإنساني وNTJ حقوق اللاجئين والمنظمات الدولية.",
    initials: "سم",
    hue: "from-purple-500 to-fuchsia-600",
    whatsapp: "+9647516667788",
    telegram: "@lawyer_sanaa",
  },
  {
    id: "l41",
    name: "الأستاذ أياد مشعان",
    slug: "iyad-moshaan",
    city: "كركوك",
    specialization: "القانون الجنائي",
    experience: 19,
    rating: 4.7,
    reviews: 167,
    verified: true,
    price: 55,
    online: false,
    gender: "male",
    languages: ["العربية", "الكردية"],
    bio: "محامٍ جنائي مخضرم يمثّل في قضايا الجرائم الإلكترونية والاحتيال المالي.",
    initials: "أم",
    hue: "from-slate-700 to-slate-900",
    whatsapp: "+9647708887766",
    telegram: "@lawyer_iyad",
  },
  {
    id: "l42",
    name: "المحامية أسماء قيس",
    slug: "asmaa-qais",
    city: "البصرة",
    specialization: "الأحوال الشخصية",
    experience: 10,
    rating: 4.9,
    reviews: 132,
    verified: true,
    price: 45,
    online: true,
    gender: "female",
    languages: ["العربية"],
    bio: "متخصصة في التسويات الودية في قضايا الطلاق والأحوال الشخصية بالPECية.",
    initials: "أق",
    hue: "from-amber-500 to-orange-600",
    whatsapp: "+9647815556677",
    telegram: "@lawyer_asmaa",
  },
  {
    id: "l43",
    name: "الأستاذ رائد شريف",
    slug: "raed-sharif",
    city: "بغداد",
    specialization: "القانون العقاري",
    experience: 16,
    rating: 4.7,
    reviews: 156,
    verified: true,
    price: 55,
    online: true,
    gender: "male",
    languages: ["العربية", "الإنجليزية"],
    bio: "خبير عقاري متخصص في صفقات البيع الكبيرة والmortgages العقارية وNTJ المنازعات.",
    initials: "رش",
    hue: "from-blue-600 to-indigo-700",
    whatsapp: "+9647706665544",
    telegram: "@lawyer_raed",
  },
  {
    id: "l44",
    name: "المحامية دلال سعيد",
    slug: "dalal-saeed",
    city: "السليمانية",
    specialization: "قانون العمل",
    experience: 8,
    rating: 4.6,
    reviews: 62,
    verified: false,
    price: 35,
    online: true,
    gender: "female",
    languages: ["العربية", "الكردية"],
    bio: "متحمسة لحماية حقوق العاملات في القطاع الخاص ومنازعات التوظيف.",
    initials: "دس",
    hue: "from-teal-500 to-emerald-600",
    whatsapp: "+9647513334455",
    telegram: "@lawyer_dalal",
  },
  {
    id: "l45",
    name: "الأستاذ بدر ناصر",
    slug: "badr-nasser",
    city: "الناصرية",
    specialization: "القانون التجاري",
    experience: 13,
    rating: 4.8,
    reviews: 109,
    verified: true,
    price: 50,
    online: true,
    gender: "male",
    languages: ["العربية", "الإنجليزية"],
    bio: "مستشار تجاري متخصص في تأسيس الشركات وNTJ العقود التجارية الكبرى.",
    initials: "بن",
    hue: "from-indigo-600 to-blue-700",
    whatsapp: "+9647823334455",
    telegram: "@lawyer_badr",
  },
  {
    id: "l46",
    name: "المحامية وجدان فيصل",
    slug: "wajdan-faisal",
    city: "الحلة",
    specialization: "القانون الصحي",
    experience: 4,
    rating: 4.5,
    reviews: 31,
    verified: false,
    price: 25,
    online: true,
    gender: "female",
    languages: ["العربية"],
    bio: "中新 في القانون الصحي وNTJ مسؤولية المستشفيات والتأمين الطبي.",
    initials: "وف",
    hue: "from-rose-500 to-pink-600",
    whatsapp: "+9647704443322",
    telegram: "@lawyer_wajdan",
  },
  {
    id: "l47",
    name: "الأستاذ عمران حسن",
    slug: "imran-hassan",
    city: "الكوت",
    specialization: "القانون الدستوري",
    experience: 20,
    rating: 4.7,
    reviews: 178,
    verified: true,
    price: 60,
    online: false,
    gender: "male",
    languages: ["العربية"],
    bio: "خبير في القانون الدستوري والانتخابات والنظام السياسي العراقي.",
    initials: "عح",
    hue: "from-emerald-500 to-teal-600",
    whatsapp: "+9647811112233",
    telegram: "@lawyer_imran",
  },
  {
    id: "l48",
    name: "المحامية ليلى بوعلام",
    slug: "leila-boualam",
    city: "بغداد",
    specialization: "القانون الدولي",
    experience: 12,
    rating: 4.8,
    reviews: 121,
    verified: true,
    price: 55,
    online: true,
    gender: "female",
    languages: ["العربية", "الفرنسية", "الإنجليزية"],
    bio: "متخصصة في القانون الدولي الخاص والمعاملات العابرة للحدود والتحكيم التجاري.",
    initials: "لب",
    hue: "from-blue-500 to-cyan-600",
    whatsapp: "+9647827776655",
    telegram: "@lawyer_leila",
  },
  {
    id: "l49",
    name: "الأستاذ زيد مجيد",
    slug: "zaid-majid",
    city: "دهوك",
    specialization: "القانون العقاري",
    experience: 15,
    rating: 4.6,
    reviews: 103,
    verified: true,
    price: 50,
    online: true,
    gender: "male",
    languages: ["العربية", "الكردية"],
    bio: "خبير عقاري متخصص في تسجيل الأراضي الزراعية وحل منازعات الحدود.",
    initials: "زم",
    hue: "from-red-500 to-rose-600",
    whatsapp: "+9647512221133",
    telegram: "@lawyer_zaid",
  },
  {
    id: "l50",
    name: "المحامية شهد عدنان",
    slug: "shahd-adnan",
    city: "الموصل",
    specialization: "الأحوال الشخصية",
    experience: 9,
    rating: 4.9,
    reviews: 97,
    verified: true,
    price: 40,
    online: true,
    gender: "female",
    languages: ["العربية"],
    bio: "متخصصة في قضايا الحضانة والنفقة والميراث بمنطق إنساني وواقعي.",
    initials: "شع",
    hue: "from-amber-500 to-orange-600",
    whatsapp: "+9647819998877",
    telegram: "@lawyer_shahd",
  },
];

export type Article = {
  id: string;
  category: string;
  title: string;
  excerpt: string;
  author: string;
  lawyerId: string;
  date: string;
  readingTime: number;
  hue: string;
  views: number;
  status?: "draft" | "pending" | "published" | "rejected";
  slug?: string;
  tags?: string[];
};

export const articles: Article[] = [
  {
    id: "a1",
    category: "الأحوال الشخصية",
    title: "كل ما تحتاج معرفته عن حضانة الأطفال بعد الطلاق في القانون العراقي",
    excerpt:
      "دليل شامل يشرح سن الحضانة ومعايير المحكمة في منح الحضانة وكيفية نقلها أو انتزاعها.",
    author: "المحامية سارة ناصر",
    lawyerId: "l2",
    date: "2025-12-10",
    readingTime: 6,
    hue: "from-amber-400 to-orange-500",
    views: 1243,
  },
  {
    id: "a2",
    category: "القانون العقاري",
    title: "إجراءات تسجيل العقار الجديد في دائرة التسجيل العقاري خطوة بخطوة",
    excerpt:
      "شرح وثائق الملكية ودور الكاتب العدل ورسوم التسجيل والمدة الزمنية المتوقعة.",
    author: "المحامية هدى كريم",
    lawyerId: "l6",
    date: "2025-12-04",
    readingTime: 8,
    hue: "from-purple-400 to-fuchsia-500",
    views: 987,
  },
  {
    id: "a3",
    category: "قانون العمل",
    title: "حقوق العامل عند الفصل التعسفي ومكافأة نهاية الخدمة",
    excerpt:
      "كيف تحسب مكافأة نهاية الخدمة ومتى يُعد الفصل تعسفياً والإجراءات القانونية للطعن.",
    author: "المحامية رنا جاسم",
    lawyerId: "l4",
    date: "2025-11-28",
    readingTime: 5,
    hue: "from-emerald-400 to-teal-500",
    views: 2105,
  },
  {
    id: "a4",
    category: "القانون الجنائي",
    title: "ضمانات المتهم في مرحلة التحقيق الأولي وفق قانون أصول المحاكمات",
    excerpt:
      "حق الصمت وحضور المحامي وإشعار المتهم بأسباب التوقيف وفق أحدث التعديلات.",
    author: "الأستاذ خالد العبيدي",
    lawyerId: "l3",
    date: "2025-11-20",
    readingTime: 7,
    hue: "from-slate-500 to-slate-700",
    views: 1567,
  },
  {
    id: "a5",
    category: "الأحوال الشخصية",
    title: "النفقة الزوجية في القانون العراقي: المستحق وشروط المطالبة وطرق التنفيذ",
    excerpt:
      "متى تجب النفقة وكيف تُقدّر وما الإجراءات القانونية عند امتناع الزوج عن الدفع.",
    author: "المحامية سارة ناصر",
    lawyerId: "l2",
    date: "2025-11-15",
    readingTime: 6,
    hue: "from-amber-400 to-orange-500",
    views: 890,
  },
  {
    id: "a6",
    category: "القانون العقاري",
    title: "الفرق بين الملكية المشتركة والملكية الفردية في قانون التسجيل العقاري",
    excerpt:
      "كيف يتم تسجيل العقار المشترك وما حقوق كل شريك وإجراءات القسمة والبيع.",
    author: "المحامية هدى كريم",
    lawyerId: "l6",
    date: "2025-11-10",
    readingTime: 7,
    hue: "from-purple-400 to-fuchsia-500",
    views: 756,
  },
  {
    id: "a7",
    category: "الأحوال الشخصية",
    title: "إثبات النسب في القانون العراقي: الطرق الحديثة والقديمة",
    excerpt:
      "كيف يثبت النسب بالفراش والإقرار والبينة وفحوصات DNA وفق التشريعات العراقية.",
    author: "المحامية سارة ناصر",
    lawyerId: "l2",
    date: "2025-11-05",
    readingTime: 8,
    hue: "from-amber-400 to-orange-500",
    views: 1432,
  },
];

export const services = [
  { id: "s1", title: "الاستشارة القانونية", icon: Scale, desc: "تحدث مع محامٍ مختص فوراً عبر الدردشة أو الهاتف." },
  { id: "s2", title: "صياغة العقود", icon: FileText, desc: "عقود عمل وتأسيس شركات واتفاقيات موثقة قانونياً." },
  { id: "s3", title: "الشركات", icon: Building2, desc: "تأسيس وإدارة الشركات والامتثال التنظيمي." },
  { id: "s4", title: "الوراثة", icon: Network, desc: "تقسيم التركات وإصدار شهادات الحصر الوراثي." },
  { id: "s5", title: "القضايا المدنية", icon: Gavel, desc: "تمثيل في المنازعات المالية والعقارية." },
  { id: "s6", title: "القضايا الجنائية", icon: ShieldCheck, desc: "دفاع احترافي أمام المحاكم الجزائية." },
  { id: "s7", title: "قضايا الأسرة", icon: HeartHandshake, desc: "طلاق وحضانة ونفقة بخصوصية ورعاية." },
  { id: "s8", title: "قضايا العمل", icon: Users, desc: "حماية حقوق العامل ومنازعات التوظيف." },
  { id: "s9", title: "العقارات", icon: Landmark, desc: "تسجيل وبيع وشراء وإدارة الأملاك." },
  { id: "s10", title: "قانون الأعمال", icon: Briefcase, desc: "استشارات تجارية واستثمارية متكاملة." },
];

export const features = [
  { id: "f1", title: "محامون موثوقون", desc: "نتحقق من ترخيص وهوية كل محامٍ قبل نشر ملفه.", icon: ShieldCheck },
  { id: "f2", title: "معلومات موثقة", desc: "نصوص القوانين مأخوذة من المصادر الرسمية ومحدثة.", icon: FileText },
  { id: "f3", title: "قوانين عراقية محدثة", desc: "أحدث التعديلات والتشريعات النافذة أولاً بأول.", icon: Scale },
  { id: "f4", title: "بحث سريع", desc: "وصول فوري لأي مادة قانونية أو محامٍ خلال ثوانٍ.", icon: Sparkles },
  { id: "f5", title: "منصة آمنة", desc: "تشفير كامل لبياناتك وخصوصية مضمونة.", icon: ShieldCheck },
  { id: "f6", title: "دعم احترافي", desc: "فريق متخصص يجيب على استفساراتك على مدار الساعة.", icon: Users },
];

export const testimonials = [
  {
    id: "t1",
    name: "أحمد الراشد",
    role: "رائد أعمال",
    rating: 5,
    text: "وفرت عليّ المنصة أسابيع من البحث. وجدت محامياً متخصصاً في تأسيس الشركات خلال دقائق.",
    initials: "أر",
    hue: "from-blue-500 to-indigo-600",
  },
  {
    id: "t2",
    name: "منى الكعبي",
    role: "موظفة حكومية",
    rating: 5,
    text: "استشرت محامية في قضية حضانة وحصلت على إجابة دقيقة ومطمئنة في نفس اليوم.",
    initials: "مك",
    hue: "from-amber-500 to-orange-600",
  },
  {
    id: "t3",
    name: "كريم العبيدي",
    role: "تاجر",
    rating: 4,
    text: "مكتبة القوانين منظمة بشكل رائع. أستطيع الرجوع لأي مادة قانونية بسهولة وسرعة.",
    initials: "كع",
    hue: "from-emerald-500 to-teal-600",
  },
];

export const faqs = [
  {
    q: "كيف يمكنني البحث عن مادة قانونية محددة؟",
    a: "استخدم صندوق البحث في الصفحة الرئيسية أو صفحة القوانين، ويمكنك البحث برقم القانون أو اسمه أو نص المادة. النتائج تظهر فوراً مع رابط المادة الكامل.",
  },
  {
    q: "هل المحامون المعروضون موثقون؟",
    a: "نعم، كل محامٍ يظهر على المنصة يحمل شارة (موثق) بعد التحقق من رخصة مزاولة المهنة وهويته من نقابة المحامين العراقيين.",
  },
  {
    q: "هل الاستشارة الأولى مدفوعة؟",
    a: "يحدد كل محامٍ سعر الاستشارة المعروض على ملفه بوضوح قبل الحجز، وتوجد خيارات استشارات أولية بأسعار رمزية.",
  },
  {
    q: "هل النصوص القانونية محدثة؟",
    a: "نعم، نعتمد المصادر الرسمية لقرارات مجلس النواب والجريدة الوقائع العراقية، ونحدّث المحتوى فور صدور أي تعديل.",
  },
  {
    q: "هل يمكنني حفظ القوانين والمحامين المفضلين؟",
    a: "بالتأكيد، يمكنك إضافة المواد القانونية والمحامين إلى المفضلة ومتابعة ما استعرضته مؤخراً من حسابك.",
  },
  {
    q: "كيف أتواصل مع الدعم الفني؟",
    a: "عبر نموذج التواصل في الصفحة أو قنوات التواصل الاجتماعي المدرجة في التذييل، ويفر فريقنا الرد خلال ساعات.",
  },
];

export const cities = ["بغداد", "أربيل", "البصرة", "النجف", "كربلاء", "الموصل", "السليمانية", "الديوانية"];
export const specializations = [
  "القانون المدني",
  "قانون العقوبات",
  "الأحوال الشخصية",
  "قانون العمل",
  "القانون التجاري",
  "القانون الإداري",
  "العقارات",
];
export const languages = ["العربية", "الكردية", "الإنجليزية", "الفرنسية"];

export const stats = [
  { value: 100000, suffix: "+", label: "مادة قانونية" },
  { value: 5000, suffix: "+", label: "محامٍ" },
  { value: 50000, suffix: "+", label: "مستخدم" },
];

export type LawFirm = {
  id: string;
  name: string;
  city: string;
  address: string;
  phones: string[];
  email?: string;
  lawyers: { name: string; specialization: string; hue: string }[];
  hue: string;
};

export const lawFirms: LawFirm[] = [
  {
    id: "f-baghdad-central",
    name: "مكتب العدالة المركزي",
    city: "بغداد",
    address: "الكرخ — شارع الرشيد، بناية النخبة، الطابق 4",
    phones: ["+964 770 111 2233", "+964 780 444 5566"],
    email: "info@aladala.example",
    hue: "from-blue-600 to-indigo-700",
    lawyers: [
      { name: "أ.د. محمد عبد الكريم", specialization: "القانون المدني", hue: "from-blue-600 to-indigo-700" },
      { name: "المحامية رنا جاسم", specialization: "قانون العمل", hue: "from-emerald-500 to-teal-600" },
      { name: "الأستاذ ياسر العاني", specialization: "القانون الإداري", hue: "from-indigo-600 to-blue-700" },
    ],
  },
  {
    id: "f-arbil-trust",
    name: "مكتب الأمانة للاستشارات القانونية",
    city: "أربيل",
    address: "شارع 60 متر — مجمع كوردستان بلازا، الطابق 2",
    phones: ["+964 750 222 3344", "+964 751 555 6677"],
    hue: "from-amber-500 to-orange-600",
    lawyers: [
      { name: "المحامية سارة ناصر", specialization: "الأحوال الشخصية", hue: "from-amber-500 to-orange-600" },
      { name: "المحامية ليلى حسن", specialization: "الأحوال الشخصية", hue: "from-rose-500 to-pink-600" },
    ],
  },
  {
    id: "f-basra-legal",
    name: "مكتب الجنوب للحقوق",
    city: "البصرة",
    address: "العشار — قرب متنزه البصرة، بناية الفيحاء",
    phones: ["+964 770 333 4455", "+964 781 666 7788"],
    email: "south@legal.example",
    hue: "from-slate-700 to-slate-900",
    lawyers: [
      { name: "الأستاذ خالد العبيدي", specialization: "القانون الجنائي", hue: "from-slate-700 to-slate-900" },
      { name: "الأستاذ عمر فؤاد", specialization: "القانون التجاري", hue: "from-blue-500 to-cyan-600" },
    ],
  },
  {
    id: "f-karbala-realestate",
    name: "مكتب الوثاق العقاري",
    city: "كربلاء",
    address: "شارع العباس — مجمع الوثاق التجاري، الطابق 3",
    phones: ["+964 770 444 5566", "+964 782 777 8899"],
    hue: "from-purple-500 to-fuchsia-600",
    lawyers: [
      { name: "المحامية هدى كريم", specialization: "العقارات", hue: "from-purple-500 to-fuchsia-600" },
    ],
  },
  {
    id: "f-mosul-justice",
    name: "مكتب العدالة للمحاماة",
    city: "الموصل",
    address: "شارع 17 تموز — مجمع المحاكم، الطابق 1",
    phones: ["+964 751 888 9900", "+964 781 555 6677"],
    email: "mosul@justice.example",
    hue: "from-emerald-500 to-teal-600",
    lawyers: [
      { name: "المحامية نور سالم", specialization: "القانون الصحي", hue: "from-emerald-500 to-teal-600" },
      { name: "الأستاذ ماجد جلال", specialization: "القانون العقاري", hue: "from-blue-500 to-cyan-600" },
      { name: "المحامية شهد عدنان", specialization: "الأحوال الشخصية", hue: "from-amber-500 to-orange-600" },
    ],
  },
  {
    id: "f-najaf-hikma",
    name: "مكتب الحكمة للاستشارات",
    city: "النجف",
    address: "شارع الإمام علي — بناية الزهراء، الطابق 3",
    phones: ["+964 782 555 6677", "+964 770 999 8877"],
    email: "najaf@hikma.example",
    hue: "from-indigo-600 to-blue-700",
    lawyers: [
      { name: "المحامية فاطمة حسين", specialization: "القانون الدستوري", hue: "from-purple-500 to-fuchsia-600" },
      { name: "الأستاذ جمال قاسم", specialization: "القانون المدني", hue: "from-indigo-600 to-blue-700" },
      { name: "الأستاذ مصطفى كاظم", specialization: "القانون المالي", hue: "from-blue-500 to-cyan-600" },
    ],
  },
  {
    id: "f-karbala-nassir",
    name: "مكتب الناصرين للاستشارات القانونية",
    city: "كربلاء",
    address: "شارع الحسين — مجمع الناصرين التجاري، الطابق 2",
    phones: ["+964 770 777 8899", "+964 751 777 8899"],
    hue: "from-amber-500 to-orange-600",
    lawyers: [
      { name: "المحامية سماح توفيق", specialization: "الأحوال الشخصية", hue: "from-amber-500 to-orange-600" },
      { name: "المحامية هبة الله عبدالله", specialization: "القانون البيئي", hue: "from-rose-500 to-pink-600" },
    ],
  },
  {
    id: "f-erbil-kurdistan",
    name: "مكتب كوردستان للقانون",
    city: "أربيل",
    address: "شارع 60 متر — برج كوردستان، الطابق 5",
    phones: ["+964 750 444 5566", "+964 751 666 7788"],
    email: "info@kurdistan-law.example",
    hue: "from-blue-600 to-indigo-700",
    lawyers: [
      { name: "المحامية ريم عباس", specialization: "الملكية الفكرية", hue: "from-blue-600 to-indigo-700" },
      { name: "المحامية سناء محمود", specialization: "القانون الدولي", hue: "from-purple-500 to-fuchsia-600" },
      { name: "الأستاذ باسل رياض", specialization: "القانون التجاري", hue: "from-slate-700 to-slate-900" },
    ],
  },
  {
    id: "f-southern-rights",
    name: "مكتب حقوق الجنوب",
    city: "الناصرية",
    address: "شارع الحبوبي — بناية الحقوق، الطابق 1",
    phones: ["+964 770 333 4455", "+964 782 333 4455"],
    hue: "from-teal-500 to-emerald-600",
    lawyers: [
      { name: "المحامية مريم عادل", specialization: "القانون البيئي", hue: "from-teal-500 to-emerald-600" },
      { name: "المحامية آلاء منصور", specialization: "القانون الإداري", hue: "from-purple-500 to-fuchsia-600" },
      { name: "الأستاذ بدر ناصر", specialization: "القانون التجاري", hue: "from-indigo-600 to-blue-700" },
    ],
  },
  {
    id: "f-baghdad-legal-center",
    name: "المركز القانوني بغدادي",
    city: "بغداد",
    address: "شارع أبو نؤاس — مجمع الحمراء، الطابق 8",
    phones: ["+964 770 111 2244", "+964 781 777 8899"],
    email: "center@baghdadi-legal.example",
    hue: "from-red-500 to-rose-600",
    lawyers: [
      { name: "الأستاذ كرار ناصر", specialization: "القانون الجنائي", hue: "from-indigo-600 to-blue-700" },
      { name: "المحامية ياسمين علي", specialization: "القانون الصحي", hue: "from-rose-500 to-pink-600" },
      { name: "الأستاذ فيصل نوري", specialization: "القانون الإداري", hue: "from-emerald-500 to-teal-600" },
      { name: "المحامية ليلى بوعلام", specialization: "القانون الدولي", hue: "from-blue-500 to-cyan-600" },
    ],
  },
];

export const navLinks = [
  { label: "الرئيسية", href: "/" },
  { label: "القوانين العراقية", href: "/laws" },
  { label: "الخدمات", href: "/services" },
  { label: "دليل المحامين", href: "/lawyers" },
  { label: "أفضل 100 محامي", href: "/top-lawyers" },
  { label: "مكاتب المحامين", href: "/law-firms" },
  { label: "المدونة", href: "/blog" },
];

// ===== Sample articles per law (real-shaped Iraqi legal content) =====
export type SampleArticle = { num: number; text: string };

export const sampleArticles: Record<string, SampleArticle[]> = {
  civil: [
    { num: 1, text: "ينظم القانون المدني العراقي رقم (40) لسنة 1951 العلاقات بين الأفراد في المعاملات المالية والشخصية، ويُعد المصدر العام للقواعد القانونية في غياب نص خاص." },
    { num: 2, text: "يُسترشد في تفسير العقود بإرادة المتعاقدين الحقيقية لا بمجرد لفظها، وعلى القاضي أن يبحث عن النية المشتركة دون الوقوف عند المعاني الحرفية للعبارات." },
    { num: 10, text: "العقد شريعة المتعاقدين، ولا يجوز نقضه ولا تعديله إلا برضاهما معاً، أو للأسباب التي يقررها القانون كالإكراه أو الغلط أو التدليس." },
    { num: 146, text: "يكون البيع باطلاً إذا كان مبيعه معدوماً وقت العقد، أما إذا هلك بعد العقد فتنتقل المسؤولية بحسب يد المشتري أو البائع وفقاً لقواعد الغصب والوديعة." },
    { num: 203, text: "تنتقل ملكية العقار بالعقد المشهر وفقاً لأحكام التسجيل العقاري، ولا يحتج بالتصرف في العقار تجاه الغير ما لم يُسجل في الدائرة المختصة." },
    { num: 906, text: "الحيازة في المنقول سند للملكية بفعل القانون، ما لم يثبت المتظلم حقه خلال المدة التي ينص عليها القانون بصورة مغايرة." },
    { num: 1245, text: "يُسأل الشخص عن الأضرار التي تلحق الغير بفعله غير المشروع، سواء كان خطأه شخصياً أو ناشئاً عن أشياء تحت يده أو عن أشخاص يسأل عنهم قانوناً." },
  ],
  penal: [
    { num: 1, text: "لا جريمة بلا نص، ولا عقوبة إلا بناءً على قانون نافذ وقت ارتكاب الفعل، ولا يُصادَر مال أحد إلا بحكم قضائي." },
    { num: 41, text: "العقوبة الأصلية هي الإعدام أو السجن المؤبد أو السجن الموقت أو الحبس أو الغرامة، وتُقدر المحكمة مقدارها ضمن الحدود المقررة لكل جريمة." },
    { num: 62, text: "يُعفى من العقاب أو يخفف عنه من كان حدثاً لم يبلغ الثامنة عشرة، ويُحكم بإيداعه إحدى مؤسسات الرعاية الاجتماعية وفق قانون الأحداث." },
    { num: 209, text: "يعاقب بالسجن كل من سلب مال الغير أو استلبها باستعمال القوة أو التهديد، وتكون العقوبة مشددة إذا اقترنت بظرف مشدد كحمل السلاح." },
    { num: 356, text: "يعاقب بالحبس كل موظف استعمل سلطة وظيفه في الاعتداء على حقوق الآخرين أو مصالحهم أو امتنع عن أداء عمل من أعمال وظيفته." },
    { num: 430, text: "لا تسري العقوبة على الأفعال التي تعدّها النصوص العقابية ضرورة دفاعاً مشروعاً عن النفس أو المال، متى كان الاعتداء حالاً وغير محق." },
  ],
  personal: [
    { num: 1, text: "يدخل في قانون الأحوال الشخصية رقم (188) لسنة 1959 ما يتعلق بالزواج والطلاق والنسب والحضانة والنفقة وغيرها من الأحوال الفردية للأشخاص." },
    { num: 3, text: "لا يصح الزواج قبل بلوغ سن الثامنة عشرة، وللمحكمة أن تأذن بزواج من أكمل الخامسة عشرة بضوابط تكفل المصلحة وتتحقق من الأهلية البدنية والعقلية." },
    { num: 34, text: "الطلاق بيد الزوج، وللمحكمة عند التفريق للضرر أو الشقاق أن تقدر نفقة العدة والمتعة بحسب يسار المطلق وحال المطلقة." },
    { num: 57, text: "حضانة الصغير حق للأم ثم للأب، ويبقى المحضون مع حاضنته حتى سن معينة تختلف باختلاف الجنس، ما لم تقرر المحكمة خلاف ذلك لمصلحة الصغير." },
    { num: 71, text: "تجب نفقة الزوجة على زوجها من تاريخ العقد الصحيح إذا سلّمت نفسها إليه، وتشمل الغذاء والكسوة والسكن وما يتبع ذلك من ضروريات." },
    { num: 113, text: "يثبت النسب بالفراش وبالإقرار وبالبينة، وللقاضي أن يأمر بإثبات النسب بالطرق العلمية المعتبرة عند النزاع وفي مصلحة المحضون." },
  ],
  labor: [
    { num: 1, text: "يسري قانون العمل رقم (37) لسنة 2015 على جميع عمال العراق وأصحاب العمل، باستثناء من هم في الخدمة العامة الخاضعين لقوانين خاصة." },
    { num: 4, text: "يُبرم عقد العمل كتابةً ويُحدد فيه الأجر والمدة والعمل المطلوب، فإن خلا من المدة كان عقداً غير محدد المدة، ويُثبت غياب الكتابة لمصلحة العامل." },
    { num: 33, text: "لا يجوز فصل العامل إلا لأسباب مبررة تتعلق بأدائه أو بظروف العمل، ويحق له التظلم أمام المحكمة العمالية خلال المدة المقررة." },
    { num: 52, text: "تُستحق مكافأة نهاية الخدمة عن كل سنة من سنوات الخدمة بقدر أجر شهر، وتُحسب على أساس الأجر الأخير الذي كان يتقاضاه العامل." },
    { num: 70, text: "تلتزم المنشأة بتوفير وسائل السلامة والصحة المهنية، ولا يجوز تشغيل العامل في ظروف تتعرض فيها حياته أو صحته للخطر بلا وقاية." },
    { num: 91, text: "للعامل الحق في أجر عن ساعات العمل الإضافية بما لا يقل عن (1.25) ضعف أجره المعتاد، ورعاية الأمومة والرضاعة وفق الضوابط المقررة." },
  ],
  traffic: [
    { num: 1, text: "يُهدف قانون المرور رقم (8) لسنة 2019 إلى تنظيم حركة المرور وحماية الأرواح والممتلكات وبيان حقوق مستعملي الطريق وواجباتهم." },
    { num: 8, text: "لا يجوز قيادة مركبة ما لم يكن السائق حاصلاً على إجازة سوق سارية المفعول تتناسب مع نوع المركبة وفئتها، وتمنح بعد اجتياز الاختبار." },
    { num: 24, text: "تُلزم قواعد المرور بربط حزام الأمان أثناء القيادة، ويمنع استخدام الهاتف النقال باليد أثناء السير، وتُضاعف الغرامة عند تكرار المخالفة." },
    { num: 39, text: "في حوادث المرور، يُحرر محضر بالواقعة ويُرسل المصاب إلى العلاج فوراً، وتفصل المحكمة المختصة في المسؤولية والتعويض عن الأضرار." },
    { num: 56, text: "تُفرض غرامة وعقوبات إدارية على السير بسرعة تتجاوز الحد المقرر، وقد تُسحب الإجازة مؤقتاً بحسب خطورة المخالفة وظروفها." },
  ],
  companies: [
    { num: 1, text: "ينظم قانون الشركات رقم (21) لسنة 1997 شكل الشركات وتأسيسها وادارتها، ويشمل شركات الأشخاص وشركات الأموال المساهمة والمحدودة." },
    { num: 10, text: "تؤسس الشركة بعقد يبيّن اسمها ونوعها ومركزها وأغراضها ورأس مالها، ويجب تسجيلها في السجل التجاري لتكتسب الشخصية المعنوية." },
    { num: 45, text: "لا يسأل الشركاء في الشركة المساهمة والمحدودة عن ديون الشركة إلا بقدر حصصهم، في حين يسأل شركاء تضامن بجميع أموالهم." },
    { num: 88, text: "تُدار الشركة المساهمة من قبل مجلس إدارة يمثلها أمام الغير، وتُعقد الجمعية العامة لإقرار الميزانية وتوزيع الأرباح وانتخاب المديرين." },
    { num: 132, text: "للشركاء حق الاطلاع على دفاتر الشركة ومستنداتها، وللأقلية حق الطعن في القرارات التي تلحق الضرر بالشركة أو بحقوقها." },
  ],
  investment: [
    { num: 1, text: "يسري قانون الاستثمار رقم (13) لسنة 2006 وتعديلاته على المشاريع الاستثمارية في القطاعات المختلفة، ويهدف إلى تشجيع رأس المال الوطني والأجنبي." },
    { num: 4, text: "يتمتع المشروع الاستثماري بالإعفاءات الضريبية والجمركية التي ينص عليها القانون للمدة المقررة، وبضمانات بعدم المصادرة أو التأميم إلا للمنفعة العامة." },
    { num: 11, text: "تُمنح إجازة للمشروع الاستثماري بعد تقديم دراسة الجدوى وتسجيله لدى الهيئة الوطنية للاستثمار أو اللجان في المحافظات." },
    { num: 19, text: "يحق للمستثمر تحويل أرباحه ورأس ماله إلى الخارج وفق الضوابط المصرفية النافذة، ويسمح بتملك الأرض اللازمة للمشروع بحدود القانون." },
    { num: 27, text: "تخضع المنازعات بين المستثمر والجهات الحكومية للتفاوض أولاً، فإن تعذر الحل فتُعرض على لجان التحكيم أو القضاء العراقي." },
  ],
  commercial: [
    { num: 1, text: "يُطبق القانون التجاري العراقي على المعاملات التي يقوم بها التاجر بقصد الاحتراف، وعلى الأوراق التجارية والعمليات البحرية والجوية." },
    { num: 12, text: "يُعد تاجراً كل من اتخذ الاتجار حرفة له واتخذ اسماً تجارياً وسجّل في السجل التجاري، ويخضع لإفلاسه وعجزه وفق أحكام هذا القانون." },
    { num: 64, text: "الكمبيالة والسند لأمر والشيك أوراق تجارية قابلة للتداول، وتكون لها حجية الإثبات وتُطبق عليها مدة التقادم المقررة قانوناً." },
    { num: 145, text: "في الإفلاس تُجمع أموال المدين وتُصفى لتوزيع ثمنها على الدائنين بحسب مرتبتهم، وللمحكمة أن تأمر بإعادة التأهيل بعد استيفاء الشروط." },
    { num: 233, text: "تخضع عقود النقل والوكالة التجارية والحساب الجاري لأحكام خاصة تكفل سرعة الفصل في المنازعات وتدفق المعاملات التجارية." },
  ],
  default: [
    { num: 1, text: "يُعد هذا القانون إطاراً تنظيمياً لأحكامه، ويعمل به من تاريخ نشره في الجريدة الرسمية ما لم ينص على خلاف ذلك." },
    { num: 5, text: "تُفسَّر نصوص القانون وفقاً لمقاصدها العامة، وعلى القاضي سد النقص بالرجوع إلى قواعد الشريعة وأعراف المعاملات والقواعد العامة." },
    { num: 12, text: "يُنشر هذا القانون في الجريدة الرسمية ويُعمال به من تاريخ صدوره، ويلغى كل نص يخالفه أو يتعارض مع أحكامه." },
  ],
};

// ===== Blog article bodies (distinct real content per article) =====
export type ArticleBlock = { h?: string; p: string };

export const articleBodies: Record<string, ArticleBlock[]> = {
  a1: [
    { p: "أصبحت العقود الإلكترونية جزءاً لا يتجزأ من الحياة اليومية في العراق، سواء في البيع عبر المتاجر الإلكترونية أو في عقود العمل عن بُعد واتفاقات الخدمات." },
    { h: "أولاً: المركز القانوني للعقد الإلكتروني", p: "يعترف القانون المدني والقواعد المستقرة بأن العقد ينعقد باتفاق إرادتين، ولا يشترط القانون شكلاً كتابياً في الأصل، فيُصح العقد الإلكتروني متى توافرت الرضا والمحل والسبب المشروع." },
    { h: "ثانياً: الإثبات وحفظ الأدلة", p: "يُنصح بتوثيق المحادثات والإيصالات والبريد الإلكتروني، لأنها تُعد أدلة معتبرة أمام المحكمة عند النزاع، وكلما زادت الوسائل المؤكدة للرضا قلّت مخاطر الإنكار." },
    { h: "ثالثاً: نصائح قبل التوقيع", p: "اقرأ الشروط والأحكام بعناية، وتأكد من هوية المتعاقد وصفته، واحتفظ بإيصال الدفع، واستشر محامياً قبل الالتزام بمبالغ كبيرة أو عقود طويلة الأجل." },
  ],
  a2: [
    { p: "يُعد قانون الأحوال الشخصية العراقي من أكثر القوانين تماساً مع حياة المواطن، ومعرفة الحقوق في الطلاق والحضانة تُوفر على الأسر كثيراً من المنازعات." },
    { h: "أولاً: حقوق المطلقة", p: "تستحق المطلقة نفقة العدة والمتعة بحسب يسار المطلق وحالها، ولها الرجوع للمحكمة لتقديرها عند النزاع، ولا تسقط هذه الحقوق بمضي مدة قصيرة دون مطالبة." },
    { h: "ثانياً: الحضانة ومصلحة الصغير", p: "تُفضَّل حضانة الأم ما دامت صالحةً وراعيةً لمصلحة المحضون، ويتدرج الانتقال إلى الأب أو غيره بحسب سن الصغير وجنسه ومصلحته الفضلى." },
    { h: "ثالثاً: التوثيق أمام المحكمة", p: "لا يكفي الاتفاق الشفوي بين الزوجين، بل يُفضّل توثيق الحقوق بقرار قضائي ينفذ جبراً، ويُسهل ذلك تحصيل النفقة عبر التنفيذ المباشر." },
  ],
  a3: [
    { p: "يوفر قانون العمل العراقي ضمانات أساسية للعامل، لكن كثيراً من العمال يجهلون كيفية المطالبة بحقوقهم عند الفصل أو عند استحقاق مكافأة نهاية الخدمة." },
    { h: "أولاً: مكافأة نهاية الخدمة", p: "تُحسب المكافأة عن كل سنة خدمة بقدر أجر شهر على أساس الأجر الأخير، وتستحق كاملة عند انتهاء العقد لأي سبب كان بما فيه الاستقالة بعد مدة محددة." },
    { h: "ثانياً: الفصل التعسفي", p: "لا يجوز فصل العامل إلا لسبب مبرر، وله التظلم أمام المحكمة العمالية في المدة القانونية، ولمحكمة الموضوع سلطة تقدير مدى مشروعية الفصل." },
    { h: "ثالثاً: خطوات عملية", p: "احتفظ بصورة من عقد العمل وكتاب التكليف، وسجّل ساعات العمل الإضافي، وراجع دائرة العمل والتوظيف قبل اتخاذ أي إجراء انفرادي." },
  ],
  a4: [
    { p: "شهد مناخ الاستثمار في العراق تطوراً تشريعياً عبر قانون الاستثمار وتعديلاته، غير أن المستثمر يحتاج لمعرفة الضمانات الفعلية قبل الدخول في أي مشروع." },
    { h: "أولاً: الضمانات والإعفاءات", p: "يتمتع المشروع الاستثماري بالإعفاءات الضريبية والجمركية للمدة المقررة، وبضمان عدم المصادرة أو التأميم إلا للمنفعة العامة وبتعويض عادل." },
    { h: "ثانياً: إجراءات التأسيس", p: "تُبدأ الخطوات بتقديم دراسة جدوى إلى الهيئة الوطنية للاستثمار أو لجان المحافظات، ثم الحصول على إجازة المشروع والسجل التجاري والأرض اللازمة." },
    { h: "ثالثاً: تحويل الأرباح والمنازعات", p: "يحق للمستثمر تحويل أرباحه وفق الضوابط المصرفية، وتُحل المنازعات بالتفاوض فالتحكيم فالقضاء، ويوصى بصياغة عقد تأسيس دقيق بلغة واضحة." },
  ],
  a5: [
    { p: "النفقة الزوجية حق ثابت للزوجة في القانون العراقي، تجب على الزوج من تاريخ العقد الصحيح متى سلّمت الزوجة نفسها إليه." },
    { h: "أولاً: شروط استحقاق النفقة", p: "تشمل شروط النفقة صحة العقد وتسليم الزوجة نفسها وطاعتها لزوجها فيما لا يخالف الشرع والقانون، وتسقط النفقة عند نشوز الزوجة أو امتناعها عن السكنى دون سبب مشروع." },
    { h: "ثانياً: تقدير النفقة", p: "تُقدَّر النفقة بحسب يسار الزوج وإعساره، وتشمل الغذاء والكسوة والسكن والعلاج، وللقاضي سلطة تقديرية واسعة في تحديد مقدارها." },
    { h: "ثالثاً: التنفيذ الجبري", p: "عند امتناع الزوج عن دفع النفقة، يجوز للزوجة اللجوء إلى التنفيذ المباشر أو الحبس التنفيذي، مع حقها في التطليق للضرر عند استمرار الامتناع." },
  ],
  a6: [
    { p: "الملكية العقارية في العراق تأخذ أشكالاً متعددة، أهمها الملكية الفردية والملكية المشتركة، ولكل منهما أحكام خاصة في قانون التسجيل العقاري." },
    { h: "أولاً: الملكية الفردية", p: "تمنح المالك حق التصرف الكامل في العقار بيعاً وشراءً ورهناً وهبة، وتُسجَّل في الدائرة العقارية المختصة لتكون حجة على الجميع." },
    { h: "ثانياً: الملكية المشتركة", p: "تقوم عندما يشترك شخصان أو أكثر في ملكية عقار واحد، ويكون لكل شريك حصة شائعة، ولا يجوز التصرف في الحصة دون مراعاة حق الشفعة للشركاء الآخرين." },
    { h: "ثالثاً: إجراءات القسمة والبيع", p: "يمكن تقسيم العقار المشترك باتفاق الشركاء أو بحكم قضائي، ويُباع العقار بالمزاد العلني عند تعذر القسمة العينية وتوزع الثمن بحسب الحصص." },
  ],
  a7: [
    { p: "إثبات النسب من أهم مسائل الأحوال الشخصية، ويحظى بحماية قانونية وشرعية واسعة في القانون العراقي لضمان حقوق الطفل والأسرة." },
    { h: "أولاً: النسب بالفراش", p: "يُثبت النسب تلقائياً للزوج إذا وُلد الطفل خلال مدة الحمل الشرعية من تاريخ العقد، وهو الأصل الشرعي والقانوني الذي لا يحتاج إثباتاً إضافياً." },
    { h: "ثانياً: الإقرار والبينة", p: "يثبت النسب بإقرار الأب أو بشهادة شهود عدول على الزواج والولادة، وللقاضي تقدير حجية البينة المقدمة." },
    { h: "ثالثاً: الفحوصات العلمية", p: "يجوز اللجوء إلى فحوصات DNA عند النزاع، وتُعد نتائجها قرينة قوية يعتد بها القاضي، خاصة في قضايا اللعان والانتفاء، مع مراعاة مصلحة المحضون الفضلى." },
  ],
};

/** HTML content for articles — richer version of articleBodies for the new BlogEditor */
function blocksToHtml(blocks: ArticleBlock[]): string {
  return blocks.map((b) => {
    let html = "";
    if (b.h) html += `<h2>${b.h}</h2>`;
    html += `<p>${b.p}</p>`;
    return html;
  }).join("\n");
}

export const articleHtml: Record<string, string> = Object.fromEntries(
  Object.entries(articleBodies).map(([id, blocks]) => [id, blocksToHtml(blocks)])
);
