import type { AdminSeo } from "./admin-data";

// Server-safe SEO defaults (NO "use client" — safe to import from
// metadata routes like app/sitemap.ts and app/robots.ts).
export const seoDefaults: AdminSeo = {
  general: {
    siteName: "منصة قانوني",
    shortName: "قانوني",
    tagline: "دليلك الذكي للقوانين العراقية",
    companyName: "منصة قانوني للخدمات القانونية",
    legalOrganization: "شركة قانوني المحدودة",
    country: "IQ",
    language: "ar",
    timezone: "Asia/Baghdad",
    logo: "/logo.png",
    defaultImage: "/og-default.png",
    email: "info@qanuni.iq",
    phone: "+964 770 000 0000",
    address: "بغداد، العراق — شارع الرشيد",
    latitude: "33.3152",
    longitude: "44.3661",
    socials: {
      facebook: "https://facebook.com/qanuni",
      twitter: "https://twitter.com/qanuni",
      instagram: "https://instagram.com/qanuni",
      linkedin: "https://linkedin.com/company/qanuni",
      youtube: "https://youtube.com/@qanuni",
      whatsapp: "+9647700000000",
      telegram: "https://t.me/qanuni",
    },
    analytics: {
      googleAnalytics: "",
      googleTagManager: "",
      searchConsole: "",
      bingWebmaster: "",
      yandex: "",
      pinterestVerification: "",
      facebookVerification: "",
    },
  },
  meta: {
    defaultTitle: "دليلك الذكي للقوانين العراقية والمحامين | منصة قانوني",
    defaultDescription:
      "ابحث في آلاف المواد القانونية العراقية، اعثر على أفضل المحامين، واقرأ أحدث المقالات القانونية في مكان واحد.",
    defaultKeywords: [
      "القوانين العراقية",
      "دليل المحامين",
      "استشارة قانونية",
      "قانون مدني",
      "قانون عقوبات",
      "الأحوال الشخصية",
      "محامي عراقي",
    ],
    titleSeparator: "|",
    titleTemplate: "%title% | %sitename%",
    descriptionTemplate: "%description%",
    autoGenerateMeta: true,
    autoTrimDescription: true,
    metaCharset: "utf-8",
    robotsDefault: "index,follow",
    canonicalDefault: true,
    authorMeta: "منصة قانوني",
    publisherMeta: "منصة قانوني",
    generatorMeta: "Next.js",
    themeColor: "#3B82F6",
    metadataBase: "https://iqlegal.example",
  },
  openGraph: {
    facebookTitle: "دليلك الذكي للقوانين العراقية والمحامين",
    facebookDescription:
      "ابحث في آلاف المواد القانونية، اعثر على أفضل المحامين، واقرأ أحدث المقالات القانونية.",
    facebookImage: "/og-default.png",
    twitterCard: "summary_large_image",
    twitterImage: "/og-default.png",
    twitterCreator: "@qanuni",
    twitterSite: "@qanuni",
    ogLocale: "ar_IQ",
    ogType: "website",
    ogSiteName: "منصة قانوني",
  },
  schema: {
    siteType: "LegalService",
    enabled: {
      Organization: true,
      LegalService: true,
      Attorney: true,
      Blog: true,
      WebSite: true,
      CollectionPage: true,
      BreadcrumbList: true,
      Article: true,
      FAQPage: true,
    },
  },
  robots: {
    global: "index,follow",
    maxImagePreview: "large",
    maxSnippet: -1,
    maxVideoPreview: -1,
  },
  canonical: {
    auto: true,
    custom: "",
    ignoreParameters: ["fbclid", "gclid", "utm_source", "utm_medium", "utm_campaign"],
    pagination: true,
    search: true,
    categories: true,
  },
  image: {
    autoAlt: true,
    autoTitle: true,
    autoCaption: false,
    autoDescription: false,
    webp: true,
    lazyLoad: true,
    imageSitemap: true,
    imageSchema: true,
  },
  breadcrumb: {
    enabled: true,
    schema: true,
    separator: "/",
    showHome: true,
    showCategory: true,
    showAuthor: false,
  },
  performance: {
    minifyCss: true,
    minifyJs: true,
    criticalCss: false,
    deferJs: true,
    lazyLoad: true,
    preloadFonts: true,
    dnsPrefetch: true,
    preconnect: true,
    http3: false,
    brotli: true,
    gzip: true,
  },
  local: {
    companyName: "منصة قانوني",
    profession: "محاماة واستشارات قانونية",
    services: ["استشارات قانونية", "توثيق عقود", "قضايا مدنية", "قضايا جنائية"],
    workingHours: "السبت - الخميس: 8:00 ص - 5:00 م",
    lat: "33.3152",
    lng: "44.3661",
    cities: ["بغداد", "البصرة", "أربيل", "الموصل", "النجف", "كربلاء"],
    governorates: ["بغداد", "البصرة", "أربيل", "نينوى", "النجف", "كربلاء"],
    googleMaps: "",
    whatsapp: "+9647700000000",
    telegram: "https://t.me/qanuni",
  },
  directory: {
    enableAttorneySchema: true,
    enableLegalServiceSchema: true,
    defaultSpecialization: "قانون مدني",
  },
  sitemap: {
    auto: true,
    split: true,
    compress: true,
    include: {
      articles: true,
      lawyers: true,
      lawFirms: true,
      courts: true,
      categories: true,
      tags: true,
      questions: true,
      pages: true,
      images: true,
      videos: false,
      news: true,
    },
  },
  redirects: [],
  notFoundMonitor: [],
  indexing: {
    googleIndexApi: false,
    bingIndexNow: false,
    instantIndex: false,
    indexNowKey: "",
  },
  ai: {
    enabled: false,
    provider: "openai",
    apiKey: "",
    autoTitle: false,
    autoDescription: false,
    autoAlt: false,
    suggestH2: true,
    suggestFaq: true,
    suggestKeywords: true,
    suggestLsi: true,
    suggestInternalLinks: true,
  },
  bulk: [],
  monitoring: {
    editLog: [],
    crawlErrors: [],
    alerts: [],
  },
};

export function getSeoDefaults(): AdminSeo {
  return seoDefaults;
}
